Trie
Niksen111/spbuProgHomeworkSem2 pull request #3
Opened 2022-03-09 14:27 UTC by Niksen111

Trie structure, with functions:
Add
Contains
Remove
HowManyStartsWithPrefix
And the Size property

2022-05-14 10:21 UTC, yurii-litvinov requested changes

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie.Tests/TestTrie.cs
> +        Trie trie = new Trie();
```suggestion
        var trie = new Trie();
```
А ещё это можно было в SetUp вынести, чтобы не писать в каждом тесте

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie.Tests/TestTrie.cs
> +        bool result = trie.Size == 0;
А это уже не нужно, просто `Assert.AreEqual(0, trie.Size);`. Тут и ниже. Библиотека юнит-тестирования берёт на себя всю вспомогательную работу.

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie.Tests/TestTrie.cs
> +                      && !trie.Contains("catla"));
А это надо разбить на отдельные assert-ы

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie.Tests/TestTrie.cs
> +        trie.Add(new string("cat"));
```suggestion
        trie.Add("cat");
```
"cat" и так string, тут Вы фактически копию строки создаёте.

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie/Program.cs
> +    public static void Main(string[] args)
Это не нужно, в Trie.csproj `<OutputType>Exe</OutputType>` замените на `<OutputType>Library</OutputType>` — библиотеке не нужна точка входа, следовательно не нужен Main

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie/Trie.cs
> +    {
Отступ лишний

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie/Trie.cs
> +        public Trie()
```suggestion
        }
        
        public Trie()
```
Все члены класса пустой строкой разделяются

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie/Trie.cs
> +            public short NumberOfWords;
```suggestion
            }
            
            public short NumberOfWords;
```

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie/Trie.cs
> +        private Node Head;
```suggestion
        private Node head;
```
Поля (кроме public-ов) именуются со строчной всегда

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie/Trie.cs
> +                    Node newNode = new Node();
```suggestion
                    var newNode = new Node();
```

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie/Trie.cs
> +            lastWord.Next.Remove(nextSymbol);
Кажется, что так нельзя делать. Например, есть у нас строки `a`, `aaa` и `aab`, хотим удалить `aab`. lastWord будет в том узле, в который мы попали по `a`, nextSymbol будет `a`, но его ещё использует строка  `aaa`. Нет?

2022-05-14 10:21 UTC, yurii-litvinov commented on 2Homework25.02.22/Trie/Trie/Trie.cs
> +        /// <summary>number of the elements</summary>
```suggestion
        }
        
        /// <summary>number of the elements</summary>
```

2022-05-31 11:37 UTC, Niksen111 commented on 2Homework25.02.22/Trie/Trie/Trie.cs
> +            lastWord.Next.Remove(nextSymbol);
Да, исправлено. Теперь вместо lastWord последнняя развилка

2022-06-05 09:05 UTC, merged